### PR TITLE
Added IsItemDeactivated

### PR DESCRIPTION
**Pull request by flamendless**

### CODE REVIEW

**Comment by MikuAuahDark** [comment]
Any idea about the use-case and an example code?

**Comment by flamendless** [comment]
Here's my use case

```
function DevTool.drawConsole()

	if Imgui.Begin("Console") then

		if Imgui.SmallButton("Show Commands History") then

			LogTable(Console.input_history, "console history")

		end

		Imgui.SameLine()

		if Imgui.SmallButton("Clear Commands History") then

			Console.clearHistory()

		end

		Imgui.SameLine()

		if Imgui.SmallButton("Clear Console Buffer") then

			Console.clearBuffer()

		end

		Console.input = Imgui.InputText("<<##Console.input", Console.input, 256)

		Console.hovered = Imgui.IsItemHovered()

		if Imgui.IsItemClicked() then

			Console.status = true

		elseif Imgui.IsItemDeactivated() then

			Console.status = false

		end

		Imgui.Separator()

		Imgui.BeginChild("scrolling##console", 0, 0, false, ImGuiWindowFlags_HorizontalScrollbar)

		if #Console.buffer > 0 then

			for i, txt in ipairs(Console.buffer) do

				Imgui.TextUnformatted(txt)

			end

		end

		Imgui.EndChild()

		Imgui.Separator()

	end

	Imgui.End()

end
```

**Comment by MikuAuahDark** [comment]
I still don't quite get it. Can you explain?

**Comment by flamendless** [comment]
You can use it with widgets like TextInput and alike. Let's say you want to change the cursor from "arrow" to "ibeam", you need to use `IsItemHovered`. If you want to disable wasd or arrow keys movement (camera) when you are interacting with the TextInput widget, you use `IsItemClicked`. Similarly, you will use `IsItemDeactivated` to change "ibeam" to "arrow" cursor when you clicked out of the TextInput widget.

That's my use case for that callback. Also, since that is a function in the latest imgui version, it should be included in the binding.

**Comment by MikuAuahDark** [comment]
> That's my use case for that callback. Also, since that is a function in the **latest imgui version**, it should be included in the binding.

Does that mean I have to update the ImGUI in this repo for it to work?

**Comment by flamendless** [comment]
No, ive already patched that in the imgui.h and imgui.cpp in the PR

**Comment by MikuAuahDark** [comment]
I'd like to know at which version of ImGUI that adds `IsItemDeactivated`. Despite the wrapper (love-imgui) is diverge from the base repo, I'd like to keep the ImGUI as-is without modification (unless for version update).

**Comment by flamendless** [comment]
According to the changelog, [here](https://github.com/ocornut/imgui/blob/62143dff64c8cfb960248b84cf6c4566ffc5a743/docs/CHANGELOG.txt#L400)

**Comment by MikuAuahDark** [comment]
Jumping from 1.53 to 1.68 looks like too much for me (breaking codes,
breaking things, any bugs you can imagine). I'll check this PR again next
week (hole I remember).

Pada tanggal Sab, 10 Agt 2019 21.59, Brandon Blanker Lim-it <
notifications@github.com> menulis:

**Comment by flamendless** [comment]
This is no longer necessary because of PR #3

**Pull request closed without merging**
