### PR TITLE
Updated to ImGui 1.73 and changed to native Dock system

### PR DESCRIPTION
**Pull request by canoi12**

### CODE REVIEW

**Comment by MikuAuahDark** [comment]
Any pointers about why `main.lua`, `compile_commands.json`, and `.clang_complete` exist?

**Comment by flamendless** [comment]
@MikuAuahDark those are generated by his ide or setup. Should be put in .gitignore

_Sent from my HUAWEI GR5 2017 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by MikuAuahDark** [comment]
Anyway @flamendless can you test his changes if it works correctly, including the dock feature?

**Comment by flamendless** [comment]
I'll test tomorrow.

**Comment by canoi12** [comment]
> Any pointers about why `main.lua`, `compile_commands.json`, and `.clang_complete` exist?

Sorry, forgot to edit .gitignore.
`compile_commands.json` is generated on compile.
`.clang_complete` is to work properly with EasyClangComplete plugin from sublime text.
And `main.lua` is just for testing

**Comment by MikuAuahDark** [comment]
It would be goos if you remove those files first.

Pada tanggal Rab, 2 Okt 2019 00.52, Canoi Gomes <notifications@github.com>
menulis:

**Comment by canoi12** [comment]
Okay, i removed the files

**Comment by flamendless** [comment]
@MikuAuahDark it seems that i can't test his PR the git way. Im doing 
```
git remote add canoi12 his-fork-url
git fetch canoi12
git fetch canoi12 pull/3/ <-----no autocomplete here in my terminal
```

However, I just did it manually by git cloning his fork. I will update the result here soon.

@canoi12  can you send me the sample main.lua so i can easily test your PR?

**Comment by canoi12** [comment]
@flamendless 
https://raw.githubusercontent.com/canoi12/love-imgui/60ad1bea4fabb7ae294b6950c795a4816690cbf3/main.lua

**Comment by flamendless** [comment]
Awesome work @canoi12 .

@MikuAuahDark  I confirm that this PR should be merged.

**Pull request merged**
